auto update at 22-04-24-23-46

diff --git a/shell/backup b/shell/backup
--- a/shell/backup
+++ b/shell/backup
@@ -11,13 +11,19 @@ pacy # Updates pac.txt so that All pacman files are the ones currently in use
 
 backup_scripts # Updates the files in the github repo full of shell scripts and conf with the ones currently in use
 
+sudo mount /dev/sda1 /mnt/backup
+
+# Check if mount was successful
+if [ $? -ne 0 ]; then
+    echo "Failed to mount /mnt/backup. Exiting..."
+    exit 1
+fi
+
 echo "Backup started at $current_date"
 
 exclude="--exclude */node_modules"
 
 cd ~/Documents
-
-sudo mount /dev/sda1 /mnt/backup
 
 borg prune --force --force --stats --list --keep-within 2d -d 31 -w 8 -m 12 -y 2 --save-space /mnt/backup
 
@@ -26,5 +32,11 @@ borg create --progress --stats --show-rc --verbose --compression lz4  /mnt/backu
 borg compact /mnt/backup
 
 sudo umount /mnt/backup
+
+# Check if unmount was successful
+if [ $? -ne 0 ]; then
+    echo "Failed to unmount /mnt/backup. Please check if any processes are still using it."
+    exit 1
+fi
 
 echo "Backup finished"
